### ISSUE TITLE
Missing config/database.sample.yml

### ISSUE THREAD

**Issue by HLFH** [ekylibre/ekylibre#2614]
The file `config/database.sample.yml` is missing.
Should be great to add it.

Such as:

```
test:
  adapter: postgis
  encoding: unicode
  database: ekylibre_test
  schema_search_path: public,postgis,lexicon
  host: localhost
  username: ekylibre # change with your DB user if needed
  password: ekylibre # change with your DB password if needed
  postgis_extension: []
development:
  adapter: postgis
  encoding: unicode
  database: ekylibre_development
  schema_search_path: public,postgis,lexicon
  host: localhost
  username: ekylibre # change with your DB user if needed
  password: ekylibre # change with your DB password if needed
  postgis_extension: []
```
